export const names = [
  "John Smith",
  "Jane Doe",
  "Michael Johnson",
  "Sarah Williams",
  "David Brown",
  "Emily Davis",
  "Christopher Miller",
  "Jessica Wilson",
  "Matthew Moore",
  "Ashley Taylor",
  "Daniel Anderson",
  "Amanda Thomas",
  "James Jackson",
  "Jennifer White",
  "Robert Harris",
  "Lisa Martin",
  "William Thompson",
  "Karen Garcia",
  "Richard Martinez",
  "Nancy Robinson",
  "Charles Clark",
  "Helen Rodriguez",
  "Joseph Lewis",
  "Dorothy Lee",
  "Thomas Walker",
  "Betty Hall",
  "Christopher Allen",
  "Sandra Young",
  "Kenneth Hernandez",
  "Donna King",
  "Mark Wright",
  "Carol Lopez",
  "Steven Hill",
  "Ruth Scott",
  "Paul Green",
  "Sharon Adams",
  "Andrew Baker",
  "Michelle Gonzalez",
  "Joshua Nelson",
  "Cynthia Carter",
  "Kenneth Mitchell",
  "Angela Perez",
  "Kevin Roberts",
  "Brenda Turner",
  "Brian Phillips",
  "Emma Campbell",
  "George Parker",
  "Olivia Evans",
  "Edward Edwards",
  "Ava Collins",
  "Ronald Stewart",
  "Sophia Sanchez",
  "Timothy Morris",
  "Isabella Rogers",
  "Jason Reed",
  "Mia Cook",
  "Jeffrey Morgan",
  "Charlotte Bell",
  "Ryan Murphy",
  "Amelia Bailey",
  "Jacob Rivera",
  "Harper Cooper",
  "Gary Richardson",
  "Evelyn Cox",
  "Nicholas Howard",
  "Abigail Ward",
  "Eric Torres",
  "Emily Peterson",
  "Jonathan Gray",
  "Elizabeth Ramirez",
  "Stephen James",
  "Sofia Watson",
  "Larry Brooks",
  "Avery Kelly",
  "Justin Sanders",
  "Ella Price",
  "Scott Bennett",
  "Chloe Wood",
  "Brandon Barnes",
  "Victoria Ross",
  "Benjamin Henderson",
  "Grace Coleman",
  "Samuel Jenkins",
  "Zoey Perry",
  "Gregory Powell",
  "Lily Long",
  "Frank Patterson",
  "Addison Hughes",
  "Raymond Flores",
  "Layla Washington",
  "Alexander Butler",
  "Natalie Simmons",
  "Patrick Foster",
  "Maya Gonzales",
  "Jack Bryant",
  "Leah Alexander",
  "Dennis Russell",
  "Hannah Griffin",
  "Jerry Diaz",
  "Zoe Hayes",
  "Tyler Myers",
];

export const roles = [
  "Aruba Central Admin",
  "Aruba Central Operator",
  "Workspace Administrator",
  "Workspace Member",
  "Workspace Observer",
  "Workspace Operator",
];

const getRandomInt = (max) => Math.ceil(Math.random() * max);

// export const subjects = names.map((name) => ({
//   role: roles.slice(0, getRandomInt(roles.length)),
//   subject: name,
//   scope: 'Global',
//   source: 'Direct',
// }));

const buildRoleAssignments = () => {
  const assignments = [];
  names.forEach((name) => {
    const roleList = roles.slice(0, getRandomInt(roles.length));
    roleList.forEach((role) => assignments.push({
      id: `${name}-${role}`,
      subject: name,
      role,
      scope: 'Global',
      source: 'Direct',
    }));
  }); 
  
  return assignments;
};
export const roleAssignments = buildRoleAssignments();